### ISSUE TITLE
For me this plugin/widget does not work (line26)

### ISSUE THREAD

**Issue by pgroot91** [enovathemes/mailchimp-widget#1]
Hi,

Thanks for this plugin widget. I'm unable to use due the following warning.

> Warning: http_build_query(): Parameter 1 expected to be Array or Object. Incorrect value given on line 26

` $url .= '?' . http_build_query($data);`

**Comment by enovathemes** [comment]
Hi, the issue comes from the data input, please check carefully the

email, fname, name, list, api_key parameters

**Comment by enovathemes** [comment]
Already available on themeforest.net

Only on themeforest.net
Live preview (https://enovathemes.us12.list-manage.com/track/click?u=f51d66947abf83c3737f089cc&id=ae6fd4ea3a&e=5091782a27)


** Equipo - Parts And Tools WordPress WooCommerce Theme
------------------------------------------------------------

Equipo is a WooCommerce WordPress theme designed for shopping online stores. Equipo includes a lot of pre-designed layouts for home page, product page to give you best selections in customization. Equipo is built based on the Tools, Equipment & Accessories website. But Equipo is also suitable for other eCommerce websites such as medical, electronic, organic, sneaker, shoes, glasses, accessories, supermarket … or anything you want.

============================================================
** Twitter (https://enovathemes.us12.list-manage.com/track/click?u=f51d66947abf83c3737f089cc&id=ac8f023222&e=5091782a27)
** Facebook (https://enovathemes.us12.list-manage.com/track/click?u=f51d66947abf83c3737f089cc&id=7be7adefe3&e=5091782a27)
** Website (https://enovathemes.us12.list-manage.com/track/click?u=f51d66947abf83c3737f089cc&id=11d6e58371&e=5091782a27)
Copyright © 2021 Enovathemes, All rights reserved.

Want to change how you receive these emails?
You can ** update your preferences (https://enovathemes.us12.list-manage.com/profile?u=f51d66947abf83c3737f089cc&id=ec80d589c7&e=5091782a27&c=b220da782e)
or ** unsubscribe from this list (https://enovathemes.us12.list-manage.com/unsubscribe?u=f51d66947abf83c3737f089cc&id=ec80d589c7&e=5091782a27&c=b220da782e)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=f51d66947abf83c3737f089cc&afl=1
